name: "Push Notification"
on: [push, pull_request]

jobs:
  ircnotify:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push' && github.repository == 'void-linux/void-packages'
        with:
          #notice: true
          channel: "#xbps"
          nickname: void-packages
          message: |-
            ${{ github.actor }} pushed to ${{ github.event.ref }}
            >>> ${{ github.event.compare }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request' && github.repository == 'void-linux/void-packages'
        with:
          #notice: true
          channel: "#xbps"
          nickname: void-packages
          message: |-
            ${{ github.actor }} opened PR
            >>> ${{ github.event.html_url }}
